/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SprintBoardRouteImport } from './routes/sprint-board'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as ImportRouteImport } from './routes/import'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfolioProjectIdRouteImport } from './routes/portfolio.$projectId'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SprintBoardRoute = SprintBoardRouteImport.update({
  id: '/sprint-board',
  path: '/sprint-board',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioProjectIdRoute = PortfolioProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => PortfolioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/import': typeof ImportRoute
  '/newsletter': typeof NewsletterRoute
  '/pipeline': typeof PipelineRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/roadmap': typeof RoadmapRoute
  '/settings': typeof SettingsRoute
  '/sprint-board': typeof SprintBoardRoute
  '/support': typeof SupportRoute
  '/portfolio/$projectId': typeof PortfolioProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/import': typeof ImportRoute
  '/newsletter': typeof NewsletterRoute
  '/pipeline': typeof PipelineRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/roadmap': typeof RoadmapRoute
  '/settings': typeof SettingsRoute
  '/sprint-board': typeof SprintBoardRoute
  '/support': typeof SupportRoute
  '/portfolio/$projectId': typeof PortfolioProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/import': typeof ImportRoute
  '/newsletter': typeof NewsletterRoute
  '/pipeline': typeof PipelineRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/roadmap': typeof RoadmapRoute
  '/settings': typeof SettingsRoute
  '/sprint-board': typeof SprintBoardRoute
  '/support': typeof SupportRoute
  '/portfolio/$projectId': typeof PortfolioProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/import'
    | '/newsletter'
    | '/pipeline'
    | '/portfolio'
    | '/roadmap'
    | '/settings'
    | '/sprint-board'
    | '/support'
    | '/portfolio/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/import'
    | '/newsletter'
    | '/pipeline'
    | '/portfolio'
    | '/roadmap'
    | '/settings'
    | '/sprint-board'
    | '/support'
    | '/portfolio/$projectId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/import'
    | '/newsletter'
    | '/pipeline'
    | '/portfolio'
    | '/roadmap'
    | '/settings'
    | '/sprint-board'
    | '/support'
    | '/portfolio/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ImportRoute: typeof ImportRoute
  NewsletterRoute: typeof NewsletterRoute
  PipelineRoute: typeof PipelineRoute
  PortfolioRoute: typeof PortfolioRouteWithChildren
  RoadmapRoute: typeof RoadmapRoute
  SettingsRoute: typeof SettingsRoute
  SprintBoardRoute: typeof SprintBoardRoute
  SupportRoute: typeof SupportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sprint-board': {
      id: '/sprint-board'
      path: '/sprint-board'
      fullPath: '/sprint-board'
      preLoaderRoute: typeof SprintBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$projectId': {
      id: '/portfolio/$projectId'
      path: '/$projectId'
      fullPath: '/portfolio/$projectId'
      preLoaderRoute: typeof PortfolioProjectIdRouteImport
      parentRoute: typeof PortfolioRoute
    }
  }
}

interface PortfolioRouteChildren {
  PortfolioProjectIdRoute: typeof PortfolioProjectIdRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioProjectIdRoute: PortfolioProjectIdRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ImportRoute: ImportRoute,
  NewsletterRoute: NewsletterRoute,
  PipelineRoute: PipelineRoute,
  PortfolioRoute: PortfolioRouteWithChildren,
  RoadmapRoute: RoadmapRoute,
  SettingsRoute: SettingsRoute,
  SprintBoardRoute: SprintBoardRoute,
  SupportRoute: SupportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
