// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://govdlkchgoffprugqdrm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvdmRsa2NoZ29mZnBydWdxZHJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI4MDk0OTIsImV4cCI6MjA5ODM4NTQ5Mn0.tx7UsclK3ZBNEyHgj5zh83vxA2-6fPiklltW1Hzfrak";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});